function [obj, grad] = editedObjective(inputVariables)
% EDITEDOBJECTIVE Compute objective function value.
% 
% Copyright 2019, The MathWorks, Inc.
%
% This function computes the objective value and gradient.
% % 
% OBJ = editedObjective(INPUTVARIABLES, EXTRAPARAMS) computes the
% objective value OBJ at the point INPUTVARIABLES, using the extra
% parameters in EXTRAPARAMS.
% 
% [OBJ, GRAD] = editedObjective(INPUTVARIABLES, EXTRAPARAMS)
% additionally computes the objective gradient value GRAD at the current
% point.
% 
% Auto-generated by prob2struct and then edited to reflect change of name 
% to 'editedObjective', insertion of gradient computation and replacing the
% definition of generatedFunction1 with its code.
% 

%% Variable indices.
idx_x = 1;
idx_y = 2;

%% Map solver-based variables to problem-based.
x = inputVariables(idx_x);
y = inputVariables(idx_y);

%% Insert gradient calculation here.
% If you include a gradient, notify the solver by setting the
% SpecifyObjectiveGradient option to true.
if nargout > 1
    grad = gradfcn(x,y);
end

%% Compute objective function.
generatedFunction1 = @(x,y)log(1+3*(y-(x.^3-x)).^2+(x-4/3).^2);
obj = generatedFunction1(x, y);

end