function [obj, grad] = generatedObjective(inputVariables, extraParams)
%generatedObjective Compute objective function value and gradient
%
%   OBJ = generatedObjective(INPUTVARIABLES, EXTRAPARAMS) computes the
%   objective value OBJ at the point INPUTVARIABLES, using the extra
%   parameters in EXTRAPARAMS.
%
%   [OBJ, GRAD] = generatedObjective(INPUTVARIABLES, EXTRAPARAMS)
%   additionally computes the objective gradient value GRAD at the current
%   point.
%
%   Auto-generated by prob2struct on 31-Jul-2023 11:51:57

%% Variable indices.
xidx = 1;
yidx = 2;

%% Map solver-based variables to problem-based.
x = inputVariables(xidx);
y = inputVariables(yidx);


%% Compute objective function.
arg2 = 3;
arg1 = (y - (x.^3 - x));
arg3 = arg1.^2;
arg4 = (x - extraParams{1});
arg5 = ((1 + (arg2 .* arg3)) + arg4.^2);
obj = log(arg5);

if nargout > 1
    %% Compute objective gradient.
    % To call the gradient code, notify the solver by setting the
    % SpecifyObjectiveGradient option to true.
    arg10 = zeros(2, 1);
    xjac = sparse(1, 1);
    yjac = sparse(1, 1);
    arg6 = (1./arg5(:));
    arg7 = (arg6.*2.*(arg4(:)));
    xjac = xjac + arg7;
    arg8 = ((arg6.*arg2(:)).*2.*(arg1(:)));
    yjac = yjac + arg8;
    arg9 = (-arg8);
    xjac = xjac + (-arg9);
    xjac = xjac + (arg9.*(3.*x(:).^2));
    arg10(xidx,:) = xjac;
    arg10(yidx,:) = yjac;
    grad = arg10(:);
end
end